name: Playwright Tests

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: |
    npm ci
    npm install -g junit-viewer
  displayName: 'install dependencies'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npm test
  displayName: 'Run Playwright cucumber tests'
- powershell: Get-ChildItem -Path . -File -Recurse
- publish: $(System.DefaultWorkingDirectory)/test-results
  artifact: playwright-report
  condition: always()
- task: PublishTestResults@2
  displayName: "Playwright-Publish Results"
  condition: always()
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: '*.xml'
    searchFolder: "$(System.DefaultWorkingDirectory)/test-results"
    testRunTitle: "Playwright Tests"

- task: PublishCucumberReport@1
  condition: always()
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: '$(System.DefaultWorkingDirectory)/test-results'
    outputPath: '$(System.DefaultWorkingDirectory)/test-results'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true

  env:
    CI: 'true'
